from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QAbstractTableModel, Qt


class Ui_SecondWindow(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(1008, 430)
        SecondWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1011, 391))
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setAutoFillBackground(True)
        self.tab.setObjectName("tab")
        self.listWidget_3 = QtWidgets.QListWidget(self.tab)
        self.listWidget_3.setGeometry(QtCore.QRect(20, 120, 61, 81))
        self.listWidget_3.setObjectName("listWidget_3")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 90, 61, 23))
        self.pushButton_13.setAutoFillBackground(False)
        self.pushButton_13.setObjectName("pushButton_13")
        self.comboBox_32 = QtWidgets.QComboBox(self.tab)
        self.comboBox_32.setGeometry(QtCore.QRect(20, 60, 61, 20))
        self.comboBox_32.setObjectName("comboBox_32")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 210, 61, 23))
        self.pushButton_14.setAutoFillBackground(False)
        self.pushButton_14.setObjectName("pushButton_14")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 60, 61, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.listWidget_4 = QtWidgets.QListWidget(self.tab)
        self.listWidget_4.setGeometry(QtCore.QRect(130, 120, 61, 81))
        self.listWidget_4.setObjectName("listWidget_4")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab)
        self.pushButton_15.setGeometry(QtCore.QRect(130, 210, 61, 23))
        self.pushButton_15.setAutoFillBackground(False)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab)
        self.pushButton_16.setGeometry(QtCore.QRect(130, 90, 61, 23))
        self.pushButton_16.setAutoFillBackground(False)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab)
        self.pushButton_17.setGeometry(QtCore.QRect(240, 210, 61, 23))
        self.pushButton_17.setAutoFillBackground(False)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab)
        self.pushButton_18.setGeometry(QtCore.QRect(240, 90, 61, 23))
        self.pushButton_18.setAutoFillBackground(False)
        self.pushButton_18.setObjectName("pushButton_18")
        self.listWidget_5 = QtWidgets.QListWidget(self.tab)
        self.listWidget_5.setGeometry(QtCore.QRect(240, 120, 61, 81))
        self.listWidget_5.setObjectName("listWidget_5")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab)
        self.pushButton_19.setGeometry(QtCore.QRect(480, 210, 61, 23))
        self.pushButton_19.setAutoFillBackground(False)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab)
        self.pushButton_20.setGeometry(QtCore.QRect(480, 90, 61, 23))
        self.pushButton_20.setAutoFillBackground(False)
        self.pushButton_20.setObjectName("pushButton_20")
        self.listWidget_6 = QtWidgets.QListWidget(self.tab)
        self.listWidget_6.setGeometry(QtCore.QRect(480, 120, 61, 81))
        self.listWidget_6.setObjectName("listWidget_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(590, 60, 61, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_21 = QtWidgets.QPushButton(self.tab)
        self.pushButton_21.setGeometry(QtCore.QRect(590, 210, 61, 23))
        self.pushButton_21.setAutoFillBackground(False)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab)
        self.pushButton_22.setGeometry(QtCore.QRect(590, 90, 61, 23))
        self.pushButton_22.setAutoFillBackground(False)
        self.pushButton_22.setObjectName("pushButton_22")
        self.listWidget_7 = QtWidgets.QListWidget(self.tab)
        self.listWidget_7.setGeometry(QtCore.QRect(590, 120, 61, 81))
        self.listWidget_7.setObjectName("listWidget_7")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_7.setGeometry(QtCore.QRect(700, 60, 61, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab)
        self.pushButton_23.setGeometry(QtCore.QRect(700, 210, 61, 23))
        self.pushButton_23.setAutoFillBackground(False)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab)
        self.pushButton_24.setGeometry(QtCore.QRect(700, 90, 61, 23))
        self.pushButton_24.setAutoFillBackground(False)
        self.pushButton_24.setObjectName("pushButton_24")
        self.listWidget_8 = QtWidgets.QListWidget(self.tab)
        self.listWidget_8.setGeometry(QtCore.QRect(700, 120, 61, 81))
        self.listWidget_8.setObjectName("listWidget_8")
        self.comboBox_13 = QtWidgets.QComboBox(self.tab)
        self.comboBox_13.setGeometry(QtCore.QRect(470, 60, 81, 22))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_12 = QtWidgets.QComboBox(self.tab)
        self.comboBox_12.setGeometry(QtCore.QRect(230, 60, 81, 22))
        self.comboBox_12.setObjectName("comboBox_12")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_8.setGeometry(QtCore.QRect(810, 60, 61, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.listWidget_9 = QtWidgets.QListWidget(self.tab)
        self.listWidget_9.setGeometry(QtCore.QRect(810, 120, 61, 81))
        self.listWidget_9.setObjectName("listWidget_9")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab)
        self.pushButton_25.setGeometry(QtCore.QRect(920, 90, 61, 23))
        self.pushButton_25.setAutoFillBackground(False)
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.tab)
        self.pushButton_26.setGeometry(QtCore.QRect(810, 210, 61, 23))
        self.pushButton_26.setAutoFillBackground(False)
        self.pushButton_26.setObjectName("pushButton_26")
        self.listWidget_10 = QtWidgets.QListWidget(self.tab)
        self.listWidget_10.setGeometry(QtCore.QRect(920, 120, 61, 81))
        self.listWidget_10.setObjectName("listWidget_10")
        self.pushButton_27 = QtWidgets.QPushButton(self.tab)
        self.pushButton_27.setGeometry(QtCore.QRect(920, 210, 61, 23))
        self.pushButton_27.setAutoFillBackground(False)
        self.pushButton_27.setObjectName("pushButton_27")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_9.setGeometry(QtCore.QRect(920, 60, 61, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton_28 = QtWidgets.QPushButton(self.tab)
        self.pushButton_28.setGeometry(QtCore.QRect(810, 90, 61, 23))
        self.pushButton_28.setAutoFillBackground(False)
        self.pushButton_28.setObjectName("pushButton_28")
        self.listWidget_11 = QtWidgets.QListWidget(self.tab)
        self.listWidget_11.setGeometry(QtCore.QRect(360, 120, 61, 81))
        self.listWidget_11.setObjectName("listWidget_11")
        self.pushButton_29 = QtWidgets.QPushButton(self.tab)
        self.pushButton_29.setGeometry(QtCore.QRect(360, 210, 61, 23))
        self.pushButton_29.setAutoFillBackground(False)
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.tab)
        self.pushButton_30.setGeometry(QtCore.QRect(360, 90, 61, 23))
        self.pushButton_30.setAutoFillBackground(False)
        self.pushButton_30.setObjectName("pushButton_30")
        self.comboBox_14 = QtWidgets.QComboBox(self.tab)
        self.comboBox_14.setGeometry(QtCore.QRect(350, 60, 81, 22))
        self.comboBox_14.setObjectName("comboBox_14")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 20, 47, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(130, 20, 61, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(250, 20, 47, 31))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(490, 20, 47, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(600, 30, 51, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(710, 30, 47, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(930, 30, 57, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(820, 20, 47, 31))
        self.label_9.setObjectName("label_9")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 250, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setAutoFillBackground(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_111 = QtWidgets.QPushButton(self.tab)
        self.pushButton_111.setGeometry(QtCore.QRect(20, 310, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_111.setFont(font)
        self.pushButton_111.setAutoFillBackground(False)
        self.pushButton_111.setObjectName("pushButton_111")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(160, 290, 221, 31))
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setObjectName("progressBar")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(390, 260, 501, 101))
        self.textBrowser.setObjectName("textBrowser")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(360, 30, 70, 17))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab)
        self.pushButton_12.setGeometry(QtCore.QRect(910, 290, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setAutoFillBackground(False)
        self.pushButton_12.setObjectName("pushButton_12")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setAutoFillBackground(True)
        self.tab_2.setObjectName("tab_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 70, 70, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_4.setGeometry(QtCore.QRect(30, 160, 70, 21))
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(130, 30, 51, 41))
        self.label_4.setObjectName("label_4")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(120, 70, 61, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(130, 120, 51, 41))
        self.label_10.setObjectName("label_10")
        self.lineEdit_100 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_100.setGeometry(QtCore.QRect(120, 160, 61, 22))
        self.lineEdit_100.setObjectName("lineEdit_100")
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setGeometry(QtCore.QRect(20, 120, 311, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setGeometry(QtCore.QRect(20, 190, 311, 41))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.tab_2)
        self.line_5.setGeometry(QtCore.QRect(10, 130, 20, 81))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.tab_2)
        self.line_6.setGeometry(QtCore.QRect(320, 130, 20, 81))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.tab_2)
        self.line_7.setGeometry(QtCore.QRect(20, 20, 311, 21))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.tab_2)
        self.line_8.setGeometry(QtCore.QRect(320, 30, 20, 81))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.tab_2)
        self.line_9.setGeometry(QtCore.QRect(20, 90, 311, 41))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.tab_2)
        self.line_10.setGeometry(QtCore.QRect(10, 30, 20, 81))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setAutoFillBackground(True)
        self.tab_3.setObjectName("tab_3")
        self.comboBox_17 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_17.setGeometry(QtCore.QRect(20, 60, 101, 22))
        self.comboBox_17.setObjectName("comboBox_17")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(50, 20, 51, 41))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab_3, "")
        SecondWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SecondWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1008, 21))
        self.menubar.setObjectName("menubar")
        SecondWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SecondWindow)
        self.statusbar.setObjectName("statusbar")
        SecondWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SecondWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

        self.comboBox_12.addItems(['softmax', 'relu', 'tanh', 'sigmoid', 'linear', 'elu'])
        self.comboBox_32.addItems(['1', '2', '3', '4', '5'])
        self.comboBox_14.addItems(['SGD', 'Adam'])
        self.comboBox_13.addItems(["mse", "mae", "binary_crossentropy", "categorical_crossentropy"])
        self.comboBox_17.addItems(["None", "MinMax", "Standard", "Robust"])

        self.label_8.setVisible(False)
        self.label_9.setVisible(False)
        self.lineEdit_8.setVisible(False)
        self.lineEdit_9.setVisible(False)
        self.listWidget_9.setVisible(False)
        self.listWidget_10.setVisible(False)
        self.pushButton_12.setEnabled(False)
        self.pushButton_25.setVisible(False)
        self.pushButton_26.setVisible(False)
        self.pushButton_27.setVisible(False)
        self.pushButton_28.setVisible(False)
        self.progressBar.setVisible(False)

        self.checkBox.stateChanged.connect(self.state_changed)

    def state_changed(self):
        if self.checkBox.isChecked() and self.listWidget_11.findItems("Adam", Qt.MatchExactly):
            self.label_8.setVisible(True)
            self.label_8.setText('Epsilon')
            self.label_9.setVisible(True)
            self.listWidget_9.setVisible(True)
            self.listWidget_10.setVisible(True)
            self.lineEdit_8.setVisible(True)
            self.lineEdit_9.setVisible(True)
            self.pushButton_25.setVisible(True)
            self.pushButton_26.setVisible(True)
            self.pushButton_27.setVisible(True)
            self.pushButton_28.setVisible(True)
        elif self.checkBox.isChecked() and self.listWidget_11.findItems("SGD", Qt.MatchExactly):
            self.label_8.setVisible(True)
            self.label_8.setText('Momentum')
            self.label_9.setVisible(True)
            self.listWidget_9.setVisible(True)
            self.listWidget_10.setVisible(True)
            self.lineEdit_8.setVisible(True)
            self.lineEdit_9.setVisible(True)
            self.pushButton_25.setVisible(True)
            self.pushButton_26.setVisible(True)
            self.pushButton_27.setVisible(True)
            self.pushButton_28.setVisible(True)
        else:
            self.label_8.setVisible(False)
            self.label_9.setVisible(False)
            self.lineEdit_8.setVisible(False)
            self.lineEdit_9.setVisible(False)
            self.listWidget_9.setVisible(False)
            self.listWidget_10.setVisible(False)
            self.pushButton_25.setVisible(False)
            self.pushButton_26.setVisible(False)
            self.pushButton_27.setVisible(False)
            self.pushButton_28.setVisible(False)


    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "Expert"))
        self.pushButton_13.setText(_translate("SecondWindow", "Add"))
        self.pushButton_14.setText(_translate("SecondWindow", "Delete"))
        self.pushButton_15.setText(_translate("SecondWindow", "Delete"))
        self.pushButton_16.setText(_translate("SecondWindow", "Add"))
        self.pushButton_17.setText(_translate("SecondWindow", "Delete"))
        self.pushButton_18.setText(_translate("SecondWindow", "Add"))
        self.pushButton_19.setText(_translate("SecondWindow", "Delete"))
        self.pushButton_20.setText(_translate("SecondWindow", "Add"))
        self.pushButton_21.setText(_translate("SecondWindow", "Delete"))
        self.pushButton_22.setText(_translate("SecondWindow", "Add"))
        self.pushButton_23.setText(_translate("SecondWindow", "Delete"))
        self.pushButton_24.setText(_translate("SecondWindow", "Add"))
        self.pushButton_25.setText(_translate("SecondWindow", "Add"))
        self.pushButton_26.setText(_translate("SecondWindow", "Delete"))
        self.pushButton_27.setText(_translate("SecondWindow", "Delete"))
        self.pushButton_28.setText(_translate("SecondWindow", "Add"))
        self.pushButton_29.setText(_translate("SecondWindow", "Delete"))
        self.pushButton_30.setText(_translate("SecondWindow", "Add"))
        self.label.setText(_translate("SecondWindow", "Hidden \n"
"Layer"))
        self.label_2.setText(_translate("SecondWindow", "Neuron for \n"
"each Layer"))
        self.label_3.setText(_translate("SecondWindow", "Activation \n"
"Function"))
        self.label_5.setText(_translate("SecondWindow", "Loss \n"
"Function"))
        self.label_6.setText(_translate("SecondWindow", "Batch Size"))
        self.label_7.setText(_translate("SecondWindow", "Epochs"))
        self.label_8.setText(_translate("SecondWindow", "Epsilon"))
        self.label_9.setText(_translate("SecondWindow", "Learning \n"
"   Rate"))
        self.pushButton_11.setText(_translate("SecondWindow", "Start \n"
"Gridsearch"))
        self.pushButton_111.setText(_translate("SecondWindow", "Start \n"
                                                              "Training"))
        self.textBrowser.setHtml(_translate("SecondWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.checkBox.setText(_translate("SecondWindow", "Optimizer"))
        self.pushButton_12.setText(_translate("SecondWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SecondWindow", "Grid Search"))
        self.checkBox_3.setText(_translate("SecondWindow", "Kfold"))
        self.checkBox_4.setText(_translate("SecondWindow", "Early Stop"))
        self.label_4.setText(_translate("SecondWindow", "Number of \n"
"    folds"))
        self.label_10.setText(_translate("SecondWindow", "Patience"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SecondWindow", "Cross Validation"))
        self.label_12.setText(_translate("SecondWindow", "  Scaler \n"
"Function"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SecondWindow", "Scaler"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondWindow()
    ui.setupUi(SecondWindow)
    SecondWindow.show()
    sys.exit(app.exec_())
